CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT UNSIGNED NOT NULL,
    email VARCHAR(255) NULL,
    display_name VARCHAR(100) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT chk_app_user_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE batch_job (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_name VARCHAR(100) NOT NULL,
    business_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    force_run TINYINT(1) NOT NULL DEFAULT 0,
    rebuild_page_only TINYINT(1) NOT NULL DEFAULT 0,
    requested_by_user_id BIGINT UNSIGNED NULL,
    started_at DATETIME(3) NOT NULL,
    ended_at DATETIME(3) NULL,
    duration_seconds INT UNSIGNED NULL,
    market_scope VARCHAR(20) NOT NULL DEFAULT 'GLOBAL',
    raw_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    processed_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    cluster_count INT UNSIGNED NOT NULL DEFAULT 0,
    page_id BIGINT UNSIGNED NULL,
    page_version_no INT UNSIGNED NULL,
    partial_message VARCHAR(500) NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    log_summary TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_batch_job_business_date_started (business_date, started_at DESC),
    KEY idx_batch_job_status_started (status, started_at DESC),
    KEY idx_batch_job_requested_by_started (requested_by_user_id, started_at DESC),
    CONSTRAINT fk_batch_job_requested_by_user FOREIGN KEY (requested_by_user_id) REFERENCES app_user(id),
    CONSTRAINT chk_batch_job_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'CANCELLED')),
    CONSTRAINT chk_batch_job_market_scope CHECK (market_scope IN ('GLOBAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE batch_job_step (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id BIGINT UNSIGNED NOT NULL,
    step_name VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    ended_at DATETIME(3) NULL,
    duration_seconds INT UNSIGNED NULL,
    input_count INT UNSIGNED NULL,
    output_count INT UNSIGNED NULL,
    partial_message VARCHAR(500) NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_batch_job_step_job_step_name (job_id, step_name),
    KEY idx_batch_job_step_job_status (job_id, status),
    CONSTRAINT fk_batch_job_step_job FOREIGN KEY (job_id) REFERENCES batch_job(id) ON DELETE CASCADE,
    CONSTRAINT chk_batch_job_step_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE batch_job_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id BIGINT UNSIGNED NOT NULL,
    log_level VARCHAR(10) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    detail_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_batch_job_log_job_created (job_id, created_at DESC),
    CONSTRAINT fk_batch_job_log_job FOREIGN KEY (job_id) REFERENCES batch_job(id) ON DELETE CASCADE,
    CONSTRAINT chk_batch_job_log_level CHECK (log_level IN ('DEBUG', 'INFO', 'WARN', 'ERROR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE news_article_raw (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_job_id BIGINT UNSIGNED NOT NULL,
    provider_name VARCHAR(50) NOT NULL,
    market_type VARCHAR(2) NOT NULL,
    business_date DATE NOT NULL,
    query_group VARCHAR(100) NOT NULL,
    provider_article_key VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    body_text MEDIUMTEXT NULL,
    publisher_name VARCHAR(255) NULL,
    author_name VARCHAR(255) NULL,
    published_at DATETIME(3) NULL,
    origin_link VARCHAR(1000) NULL,
    naver_link VARCHAR(1000) NULL,
    payload_json JSON NULL,
    collected_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_article_raw_provider_key (provider_name, provider_article_key),
    KEY idx_news_article_raw_business_market_published (business_date, market_type, published_at DESC),
    KEY idx_news_article_raw_batch_job (batch_job_id),
    CONSTRAINT fk_news_article_raw_batch_job FOREIGN KEY (batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT chk_news_article_raw_market_type CHECK (market_type IN ('US', 'KR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE news_article_processed (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_job_id BIGINT UNSIGNED NOT NULL,
    raw_article_id BIGINT UNSIGNED NULL,
    business_date DATE NOT NULL,
    market_type VARCHAR(2) NOT NULL,
    dedupe_key VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    normalized_title VARCHAR(500) NULL,
    body_text MEDIUMTEXT NULL,
    publisher_name VARCHAR(255) NULL,
    published_at DATETIME(3) NULL,
    origin_link VARCHAR(1000) NULL,
    naver_link VARCHAR(1000) NULL,
    source_summary VARCHAR(255) NULL,
    is_representative_candidate TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_article_processed_dedupe (business_date, market_type, dedupe_key),
    KEY idx_news_article_processed_business_market_published (business_date, market_type, published_at DESC),
    KEY idx_news_article_processed_batch_job (batch_job_id),
    KEY idx_news_article_processed_raw_article (raw_article_id),
    CONSTRAINT fk_news_article_processed_batch_job FOREIGN KEY (batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT fk_news_article_processed_raw_article FOREIGN KEY (raw_article_id) REFERENCES news_article_raw(id),
    CONSTRAINT chk_news_article_processed_market_type CHECK (market_type IN ('US', 'KR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE news_cluster (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cluster_id CHAR(36) NOT NULL,
    batch_job_id BIGINT UNSIGNED NOT NULL,
    business_date DATE NOT NULL,
    market_type VARCHAR(2) NOT NULL,
    title VARCHAR(500) NOT NULL,
    summary_short VARCHAR(500) NULL,
    summary_long TEXT NULL,
    analysis_json JSON NULL,
    tags_json JSON NULL,
    representative_article_id BIGINT UNSIGNED NOT NULL,
    article_count INT UNSIGNED NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    last_updated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_cluster_cluster_id (cluster_id),
    KEY idx_news_cluster_business_market_sort (business_date, market_type, sort_order),
    KEY idx_news_cluster_representative_article (representative_article_id),
    KEY idx_news_cluster_batch_job (batch_job_id),
    CONSTRAINT fk_news_cluster_batch_job FOREIGN KEY (batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT fk_news_cluster_representative_article FOREIGN KEY (representative_article_id) REFERENCES news_article_processed(id),
    CONSTRAINT chk_news_cluster_market_type CHECK (market_type IN ('US', 'KR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE news_cluster_article (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cluster_id BIGINT UNSIGNED NOT NULL,
    processed_article_id BIGINT UNSIGNED NOT NULL,
    is_representative TINYINT(1) NOT NULL DEFAULT 0,
    article_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_cluster_article_cluster_article (cluster_id, processed_article_id),
    KEY idx_news_cluster_article_cluster_order (cluster_id, article_order),
    KEY idx_news_cluster_article_article_cluster (processed_article_id, cluster_id),
    CONSTRAINT fk_news_cluster_article_cluster FOREIGN KEY (cluster_id) REFERENCES news_cluster(id) ON DELETE CASCADE,
    CONSTRAINT fk_news_cluster_article_article FOREIGN KEY (processed_article_id) REFERENCES news_article_processed(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_index_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_job_id BIGINT UNSIGNED NOT NULL,
    business_date DATE NOT NULL,
    market_type VARCHAR(2) NOT NULL,
    index_code VARCHAR(30) NOT NULL,
    index_name VARCHAR(100) NOT NULL,
    close_price DECIMAL(18,4) NOT NULL,
    change_value DECIMAL(18,4) NOT NULL,
    change_percent DECIMAL(9,4) NOT NULL,
    high_price DECIMAL(18,4) NULL,
    low_price DECIMAL(18,4) NULL,
    provider_name VARCHAR(50) NOT NULL,
    collected_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_index_daily_business_market_code (business_date, market_type, index_code),
    KEY idx_market_index_daily_batch_job (batch_job_id),
    CONSTRAINT fk_market_index_daily_batch_job FOREIGN KEY (batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT chk_market_index_daily_market_type CHECK (market_type IN ('US', 'KR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ai_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_job_id BIGINT UNSIGNED NOT NULL,
    summary_type VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    business_date DATE NOT NULL,
    market_type VARCHAR(2) NULL,
    prompt_version VARCHAR(50) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    content_json JSON NOT NULL,
    fallback_used TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_summary_target_version (summary_type, target_type, target_id, prompt_version),
    KEY idx_ai_summary_business_market_type (business_date, market_type, summary_type),
    KEY idx_ai_summary_batch_job (batch_job_id),
    CONSTRAINT fk_ai_summary_batch_job FOREIGN KEY (batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT chk_ai_summary_market_type CHECK (market_type IN ('US', 'KR') OR market_type IS NULL),
    CONSTRAINT chk_ai_summary_status CHECK (status IN ('SUCCESS', 'PARTIAL', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_daily_page (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_batch_job_id BIGINT UNSIGNED NOT NULL,
    business_date DATE NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    page_title VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    global_headline VARCHAR(500) NULL,
    generated_at DATETIME(3) NOT NULL,
    partial_message VARCHAR(500) NULL,
    raw_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    processed_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    cluster_count INT UNSIGNED NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    markets_json JSON NULL,
    article_links_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_daily_page_business_version (business_date, version_no),
    KEY idx_market_daily_page_generated_at (generated_at DESC),
    KEY idx_market_daily_page_business_version_desc (business_date, version_no DESC),
    KEY idx_market_daily_page_status_generated (status, generated_at DESC),
    CONSTRAINT fk_market_daily_page_source_batch_job FOREIGN KEY (source_batch_job_id) REFERENCES batch_job(id),
    CONSTRAINT chk_market_daily_page_status CHECK (status IN ('READY', 'PARTIAL', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_daily_page_market (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    market_type VARCHAR(2) NOT NULL,
    market_label VARCHAR(100) NOT NULL,
    summary_title VARCHAR(255) NULL,
    summary_body TEXT NULL,
    analysis_background_json JSON NULL,
    analysis_key_themes_json JSON NULL,
    analysis_outlook TEXT NULL,
    raw_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    processed_news_count INT UNSIGNED NOT NULL DEFAULT 0,
    cluster_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_updated_at DATETIME(3) NULL,
    partial_message VARCHAR(500) NULL,
    metadata_json JSON NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_daily_page_market_page_market (page_id, market_type),
    KEY idx_market_daily_page_market_page_sort (page_id, sort_order),
    CONSTRAINT fk_market_daily_page_market_page FOREIGN KEY (page_id) REFERENCES market_daily_page(id) ON DELETE CASCADE,
    CONSTRAINT chk_market_daily_page_market_type CHECK (market_type IN ('US', 'KR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_daily_page_index (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_market_id BIGINT UNSIGNED NOT NULL,
    source_index_id BIGINT UNSIGNED NULL,
    index_code VARCHAR(30) NOT NULL,
    index_name VARCHAR(100) NOT NULL,
    close_price DECIMAL(18,4) NOT NULL,
    change_value DECIMAL(18,4) NOT NULL,
    change_percent DECIMAL(9,4) NOT NULL,
    high_price DECIMAL(18,4) NULL,
    low_price DECIMAL(18,4) NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_market_daily_page_index_market_sort (page_market_id, sort_order),
    KEY idx_market_daily_page_index_source_index (source_index_id),
    CONSTRAINT fk_market_daily_page_index_page_market FOREIGN KEY (page_market_id) REFERENCES market_daily_page_market(id) ON DELETE CASCADE,
    CONSTRAINT fk_market_daily_page_index_source_index FOREIGN KEY (source_index_id) REFERENCES market_index_daily(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_daily_page_cluster (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_market_id BIGINT UNSIGNED NOT NULL,
    source_cluster_id BIGINT UNSIGNED NULL,
    cluster_id CHAR(36) NOT NULL,
    title VARCHAR(500) NOT NULL,
    summary VARCHAR(500) NULL,
    article_count INT UNSIGNED NOT NULL DEFAULT 0,
    tags_json JSON NULL,
    representative_processed_article_id BIGINT UNSIGNED NULL,
    representative_title VARCHAR(500) NULL,
    representative_publisher_name VARCHAR(255) NULL,
    representative_published_at DATETIME(3) NULL,
    representative_origin_link VARCHAR(1000) NULL,
    representative_naver_link VARCHAR(1000) NULL,
    representative_source_summary VARCHAR(255) NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_market_daily_page_cluster_market_sort (page_market_id, sort_order),
    KEY idx_market_daily_page_cluster_cluster_id (cluster_id),
    KEY idx_market_daily_page_cluster_source_cluster (source_cluster_id),
    CONSTRAINT fk_market_daily_page_cluster_page_market FOREIGN KEY (page_market_id) REFERENCES market_daily_page_market(id) ON DELETE CASCADE,
    CONSTRAINT fk_market_daily_page_cluster_source_cluster FOREIGN KEY (source_cluster_id) REFERENCES news_cluster(id) ON DELETE SET NULL,
    CONSTRAINT fk_market_daily_page_cluster_representative_article FOREIGN KEY (representative_processed_article_id) REFERENCES news_article_processed(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE market_daily_page_article_link (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    page_market_id BIGINT UNSIGNED NULL,
    processed_article_id BIGINT UNSIGNED NULL,
    cluster_id CHAR(36) NULL,
    cluster_title VARCHAR(500) NULL,
    title VARCHAR(500) NOT NULL,
    publisher_name VARCHAR(255) NULL,
    published_at DATETIME(3) NULL,
    origin_link VARCHAR(1000) NULL,
    naver_link VARCHAR(1000) NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_market_daily_page_article_link_page_sort (page_id, sort_order),
    KEY idx_market_daily_page_article_link_market_sort (page_market_id, sort_order),
    KEY idx_market_daily_page_article_link_processed_article (processed_article_id),
    CONSTRAINT fk_market_daily_page_article_link_page FOREIGN KEY (page_id) REFERENCES market_daily_page(id) ON DELETE CASCADE,
    CONSTRAINT fk_market_daily_page_article_link_page_market FOREIGN KEY (page_market_id) REFERENCES market_daily_page_market(id) ON DELETE SET NULL,
    CONSTRAINT fk_market_daily_page_article_link_processed_article FOREIGN KEY (processed_article_id) REFERENCES news_article_processed(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
